### ISSUE TITLE
Milestone 2 checklist

### ISSUE THREAD

**Issue by fishydays** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#25]
Hey guys, 
Here are the items we will need to work on for this week:
- [x] Creation and validation of  Docker file and publishing to image on DockerHub and GitHub Workflows(@Lukman-Lateef  @jinxyou)
- [x] Environment file issues fix and validation of docker (@vrudhgarg)
- [x] Data validation adn final recheck (@fishydays @shawnhu444 )
- [x] Final check and releasing on github (@jinxyou @fishydays @shawnhu444 )
