### ISSUE TITLE
Data Validation Checklist

### ISSUE THREAD

**Issue by shawnhu444** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#27]
1. Correct data file format
2. Correct column names
3. Target/response variable follows expected distribution
4. No anomalous correlations between target/response variable and features/explanatory variables
5. No anomalous correlations between features/explanatory variables

**Comment by fishydays** [comment]
Thanks, Shawn! 
These look great, here are a few more things we need to do and a complete checklist to check things off as we go:

- [ ] 1) Correct data file format
- [ ] 2) Correct column names
- [ ] 3) No empty observations
- [ ] 4) Missingness not beyond expected threshold
- [ ] 5) Correct data types in each column
- [ ] 6) No duplicate observations
- [ ] 7) No outlier or anomalous values
- [ ] 8) Correct category levels (i.e., no string mismatches or single values)
- [ ] 9) Target/response variable follows expected distribution
- [ ] 10) No anomalous correlations between target/response variable and features/explanatory variables
- [ ] 11) No anomalous correlations between features/explanatory variables

**Comment by shawnhu444** [comment]
looks good

**Comment by shawnhu444** [comment]
reopened
