### ISSUE TITLE
Issues from milestone 1

### ISSUE THREAD

**Issue by vrudhgarg** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#47]
- [x] Add env file(already added into Milestone 2)
- [x] Organization of .ipynb file into a folder. Let's fix the file structures
- [x] The email under "enforcement" should be tied to the team (Not sure about this)
- [x] Fig 1-8 not displayed in ipynb. (Maybe HTML addition fixed it? or we should add image folder and link the images?]
- [x] Many branch names are not meaningful (they should reflect the work being done on the branch).

**Comment by vrudhgarg** [comment]
Sure. All issues are resolved here! So closing it for now
