### ISSUE TITLE
Work split for milestone 3

### ISSUE THREAD

**Issue by jinxyou** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#49]
- [x] Download/extract data (@shawnhu444)
- [x] Clean/transform data (@shawnhu444)
- [x] Split and pre-process data (@fishydays )
- [x] Exploratory data analysis (@fishydays )
- [x] Model fitting (@vrudhgarg )
- [x] Model evaluation (@vrudhgarg )
- [x] README update (@shawnhu444 @fishydays @vrudhgarg )
- [x] Repo restructure (@shawnhu444 @fishydays @vrudhgarg )
- [x] Quarto intro - methods (@jinxyou )
- [x] Quarto results - discussions (@Lukman-Lateef )

**Comment by shawnhu444** [comment]
@Lukman-Lateef  Thanks.

**Comment by fishydays** [comment]
Everything looks completed, thanks everyone!
