### ISSUE TITLE
Work splits for Milestone 4

### ISSUE THREAD

**Issue by jinxyou** [UBC-MDS/DSCI522-2425-28-rental-bike-prediction#90]
- [ ] Makefile - @fishydays 
- [ ] Pytest update environment @fishydays 
- [ ] Making EDA function and tests: @shawnhu444 
- [ ] Making data validation functions and tests: @fishydays 
- [ ] Making preprocessing functions and tests: @jinxyou 
- [ ] Making model functions and tests: @vrudhgarg 
- [ ] Making model validation functions and tests: @Lukman-Lateef 
- [ ] Addressing reviews and comments: @fishydays @jinxyou @Lukman-Lateef @vrudhgarg @shawnhu444
